version: '3'
services:
  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    volumes:
      - ./postgres14:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=mastodon"
      - "POSTGRES_USER=mastodon"
      - "POSTGRES_DB=mastodon"
    ports:
      - "127.0.0.1:52871:5432"

  redis:
    restart: always
    image: redis:7-alpine
    volumes:
      - ./redis:/data
    ports:
      - "127.0.0.1:52872:6379"
